<?php
use StaticSiteExport\Module;

$canExport = Module::sitesDirectoryPathIsValid($this->setting('static_site_export_sites_directory_path'));

$this->htmlElement('body')->appendAttribute('class', 'static-site-export browse');
?>

<?php echo $this->pageTitle($this->translate('Static sites'), 1, $this->translate('Static Site Export')); ?>

<div id="page-actions">
    <?php if ($canExport): ?>
    <?php echo $this->hyperlink($this->translate('Export new static site'), $this->url(null, ['action' => 'export'], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created',
    ],
    [
        'label' => $this->translate('Name'),
        'value' => 'name',
    ],
]); ?>
</div>

<?php if ($staticSites): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Name'); ?></th>
            <th><?php echo $this->translate('Export status'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($staticSites as $staticSite): ?>
    <?php
    $job = $staticSite->job();
    $owner = $staticSite->owner();
    ?>
        <tr>
            <td>
                <?php echo $staticSite->name(); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $staticSite->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $staticSite->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $this->translate('Delete'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $job->link($this->translate($job->statusLabel())); ?></td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($staticSite->created()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo sprintf(
        $this->translate('No static sites found. %s'),
        $canExport ? $this->hyperlink($this->translate('Export new static site.'), $this->url(null, ['action' => 'export'], true)) : ''
    ); ?></p>
</div>
<?php endif; ?>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>
