<?php $form->prepare(); ?>

<?php echo $this->pageTitle($this->translate('Export static site'), 1, $this->translate('Static Site Export')); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'browse'], true), ['class' => 'button']); ?>
    <button type="submit"><?php echo $this->translate('Begin export'); ?></button>
</div>

<?php echo $this->formCollection($form); ?>

<?php echo $this->form()->closeTag(); ?>
