<?php
$job = $staticSite->job();
$owner = $staticSite->owner();
?>

<h3><?php echo $this->escapeHtml($staticSite->name()); ?></h3>

<div class="meta-group">
    <h4><?php echo $this->translate('Name'); ?></h4>
    <div class="value"><?php echo $staticSite->name(); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Export job'); ?></h4>
    <div class="value"><?php
        echo sprintf(
            $this->translate('Status: %s [%s]'),
            $job->link($job->statusLabel()),
            $job->log()
                ? $this->hyperlink($this->translate('view log'), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()]), ['target' => '_blank'])
                : $this->translate('no log')
        ); ?></div>
    <div class="value"><?php echo sprintf($this->translate('Started: %s'), $this->i18n()->dateFormat($job->started(), 'medium', 'medium')); ?></div>
    <div class="value"><?php echo sprintf($this->translate('Ended: %s'), $this->i18n()->dateFormat($job->ended(), 'medium', 'medium')); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Owner'); ?></h4>
    <div class="value"><?php echo $owner ? $owner->link($owner->name()) : ''; ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Created'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($staticSite->created(), 'medium', 'medium'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Base URL'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('base_url'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Theme'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('theme'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Include private resources'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('include_private'); ?></div>
</div>
