<?php
$job = $staticSite->job();
$owner = $staticSite->owner();
?>

<h3><?php echo $this->escapeHtml($staticSite->label()); ?></h3>

<div class="meta-group">
    <h4><?php echo $this->translate('Status'); ?></h4>
    <div class="value"><?php ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Owner'); ?></h4>
    <div class="value"><?php echo $owner ? $owner->link($owner->name()) : ''; ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Created'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($staticSite->created(), 'long', 'long'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Exclude media'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('exclude_media') ? $this->translate('True') : $this->translate('False'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Exclude item sets'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('exclude_item_sets') ? $this->translate('True') : $this->translate('False'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Exclude pages'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('exclude_pages') ? $this->translate('True') : $this->translate('False'); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Exclude private'); ?></h4>
    <div class="value"><?php echo $staticSite->dataValue('exclude_private') ? $this->translate('True') : $this->translate('False'); ?></div>
</div>
